server.port=${PORT:8080}

spring.application.name=FlowerShopOrder

logging.level.org.atmosphere=warn
spring.mustache.check-template-location=false

vaadin.launch-browser=true

spring.datasource.url=jdbc:postgresql://localhost:5432/flowershoporder
spring.datasource.username=flowershoporder
spring.datasource.password=flowershoporder
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,at.spengergasse